version: '3'
services:
  app:
    build: .
    image: flask-redis:1.0
    environment:
      - FLASK_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=iotdb
      - DB_USER=iotuser
      - DB_PASSWORD=iotpassword
    ports:
      - 5000:5000
    networks:
      - backend
      - frontend
    volumes:
      - dbdata:/database
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:4.0.11-alpine
    networks:
      - backend
    volumes:
      - dbdata:/data

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=iotdb
      - POSTGRES_USER=iotuser
      - POSTGRES_PASSWORD=iotpassword
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  backend:
  frontend:
volumes:
  dbdata:
  pgdata:

